services:
  mongo_db:
    image: 'amd64/mongo:8.0-noble'
    container_name: express-app-db
    ports:
      - '3031:27017'
    volumes:
      - express-app-data:/var/lib/mongodb/data
  express-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - MONGO_DB_URI=mongodb://mongo_db:27017/express-app
    container_name: express-app
    ports:
      - '3030:3030'
    restart: always
    depends_on:
      - mongo_db
    volumes:
      - .:/app

volumes:
  express-app-data:
